package com.ziroom.ziroomcustomer.e;

import com.ziroom.commonlib.utils.h;

public class q
{
  public static String A;
  public static String B;
  public static String C;
  public static String D;
  public static String E;
  public static String F;
  public static String G;
  public static String H;
  public static String I;
  public static String J;
  public static String K;
  public static String L;
  public static String M;
  public static String N;
  public static String O;
  public static String P;
  public static String Q;
  public static String R;
  public static String S;
  public static String T;
  public static String U;
  public static String V;
  public static String W;
  public static String X;
  public static String Y;
  public static String Z;
  public static String a = "https://interfaces.ziroom.com/";
  public static String aa;
  public static String ab;
  public static String ac;
  public static String ad;
  public static String ae;
  public static String af;
  public static String ag;
  public static String ah;
  public static String ai;
  public static String aj;
  public static String ak;
  public static String al;
  public static String am;
  public static String an;
  public static String ao;
  public static String ap;
  public static String aq;
  public static String ar;
  public static String as;
  public static String b = "https://phoenix.ziroom.com/";
  public static String c = "https://yzwebapi.ziroom.com/";
  public static String d = "https://pic.ziroom.com.cn/";
  public static String e = "https://mucenter.ziroom.com/";
  public static String f = "http://customer.ziroom.com/api/";
  public static String g;
  public static String h = "https://phoenix.ziroom.com/";
  public static String i = "http://smsapi.ziroom.com/API/";
  public static String j = "https://smsapis.ziroom.com/";
  public static String k = "https://zmcapi.ziroom.com/";
  public static String l = "https://movessmsapis.ziroom.com/";
  public static String m = "https://smswx.ziroom.com/";
  public static String n = "https://sm.ziroom.com/";
  public static String o = "https://ztoread.ziroom.com/";
  public static String p = "http://ia.ziroom.com/robot/h5chat_ZR.html?sysNum=1476067342641247";
  public static String q = "http://s.m.ziroom.com/";
  public static String r = "https://es.ziroom.com/";
  public static String s = "https://crm.ziroom.com/crm/";
  public static String t = s;
  public static String u = "https://cmch.ziroom.com/";
  public static String v = t;
  public static String w = "https://crm.ziroom.com/crm/";
  public static String x;
  public static String y;
  public static String z;
  
  static
  {
    L = "https://upin.ziroom.com/";
    M = "http://mbs.ziroom.com/";
    N = "fn7srzT88FcNiRQA3n";
    O = "https://ucenter.ziroom.com/";
    P = "8f5dc0a1d869360ec5ccad9ac302f718";
    Q = "https://kaleido.ziroom.com/";
    R = "http://i.webapi.ziroom.com/";
    S = "https://fngateway.ziroom.com/";
    T = "https://zryapi.ziroom.com/";
    U = r;
    V = "https://passport.ziroom.com/";
    W = "http://webapp.webapi.ziroom.com/";
    X = "https://zhuanti.ziroom.com/";
    Y = "https://www.ziroom.com/";
    Z = "https://apppush.ziroom.com/";
    aa = "https://contentful.ziroom.com/online/zuzhu/bjapp/ucenter/a1d0c6e83f027327d8461063f4ac58a6.json";
    ab = "http://contentful.ziroom.com/online/zuzhu/bjapp/e2230b853516e7b05d79744fbd4c9c13.json";
    ac = "kaleidoApi/customer/center/ads.json";
    ad = "contentful/ziruke-app/v1/app/layer.json";
    ae = "contentful/ziruke-app/v1/ziruyu/index.json";
    af = "https://contentful.ziroom.com/online/zuzhu/hzapp/3988c7f88ebcb58c6ce932b957b6f332.json";
    ag = "https://contentful.ziroom.com/online/ziruyu/ziruyuapp/f0935e4cd5920aa6c7c996a5ee53a70f.json";
    ah = "http://contentful.ziroom.com/online/combine/fbd7939d674997cdb4692d34de8633c4.json";
    ai = "http://yezhu.ziroom.com/m/weituo.html?header=false&from_id=26";
    aj = "http://contentful.ziroom.com/online/zuzhu/bjapp/3a029f04d76d32e79367c4b3255dda4d.json";
    ak = "https://contentful.ziroom.com/online/";
    al = "https://coupon.ziroom.com/";
    am = "http://installment.ziroom.com/";
    an = "https://wx.ziroom.com/";
    ao = "https://datapi.ziroom.com/";
    ap = "http://kaleido.ziroom.com";
    aq = "https://contentful.ziroom.com/online/combine/app/zry/v2/index.json";
    ar = "https://hd.ziroom.com/";
    as = "http://i.webapi.ziroom.com/";
    updateWeb();
  }
  
  public static void updateWeb()
  {
    if (1 == h.getsEnvironment())
    {
      a = "https://tinterfaces.ziroom.com/";
      D = "https://tpay.ziroom.com/";
      j = "http://smsapi.d.ziroom.com/";
      r = "https://tes.ziroom.com/";
      U = r;
      s = "http://10.30.121.87:8087/";
      t = s;
      u = "https://cmch.ziroom.com/";
      V = "https://tpassport.ziroom.com/";
      x = V;
      y = V;
      k = "https://dzmcapi.ziroom.com/";
      T = "https://tzryapi.ziroom.com/";
      B = T;
      E = "https://tzraapi.ziroom.com/";
      b = "https://tphoenix.ziroom.com/";
      h = b;
      e = "https://tmucenter.ziroom.com/";
      O = "https://tucenter.ziroom.com/";
      J = "https://twx.ziroom.com/";
      l = "https://dmovessmsapis.ziroom.com/";
      G = "https://tprop.ziroom.com/";
      Q = "https://tkaleido.ziroom.com/";
      q = "http://s.m.d.ziroom.com/";
      C = "https://dbnbapi.ziroom.com/";
      S = "https://tfngateway.ziroom.com/";
      ai = "https://tyezhu.ziroom.com/m/weituo.html?header=false&from_id=26";
      c = "https://tyzwebapi.ziroom.com/";
      L = "https://tupin.ziroom.com/";
      Z = "https://dapppush.ziroom.com/";
      g = "https://tphoenix.ziroom.com/";
      i = j + "API/";
      v = t;
      z = j;
      A = j;
      H = O;
      I = Q;
      m = "http://s.m.swx.d.ziroom.com/";
      n = "http://s.m.d.ziroom.com/";
      R = Q;
      K = "b29df42e480325d2e8fb6fa17fba037f";
      P = "b29df42e480325d2e8fb6fa17fba037f";
      W = "http://webapp.webapi.fp001.qa.ziroom.com/";
      o = "http://toread.d.ziroom.com/";
      p = "http://ia.t.ziroom.com/robot/h5chat_ZR.html?sysNum=1476067342641247";
      an = "https://twx.ziroom.com/";
      al = "https://tcoupon.ziroom.com/";
      ap = "http://tkaleido.ziroom.com";
      M = "http://10.30.26.79:8082/";
      X = "http://www.t.ziroom.com/";
      Y = "http://www.t.ziroom.com/";
      F = "http://zra.api.d.ziroom.com/";
      aj = "http://contentful.ziroom.com/staging/zuzhu/bjapp/3a029f04d76d32e79367c4b3255dda4d.json";
      as = "http://i.webapi.qa.ziroom.com/";
      ar = "http://www.t.ziroom.com/zhuanti/";
      am = "http://installment.t.ziroom.com/";
      return;
    }
    if (2 == h.getsEnvironment())
    {
      a = "http://tinterfaces.ziroom.com/";
      a = "https://tinterfaces.ziroom.com/";
      D = "https://tpay.ziroom.com/";
      j = "https://tsmsapis.ziroom.com/";
      r = "https://tes.ziroom.com/";
      U = r;
      s = "https://tcrm.ziroom.com/crm-reserve/";
      t = s;
      u = "https://tcmch.ziroom.com/";
      V = "https://tpassport.ziroom.com/";
      x = V;
      y = V;
      k = "https://tzmcapi.ziroom.com/";
      T = "https://tzryapi.ziroom.com/";
      B = T;
      E = "https://tzraapi.ziroom.com/";
      b = "https://tphoenix.ziroom.com/";
      h = b;
      e = "https://tmucenter.ziroom.com/";
      O = "https://tucenter.ziroom.com/";
      J = "https://qwx.ziroom.com/";
      l = "https://tmovessmsapis.ziroom.com/";
      G = "https://tprop.ziroom.com/";
      Q = "https://t1kaleido.ziroom.com/";
      q = "http://s.m.t.ziroom.com/";
      C = "https://tbnbapi.ziroom.com/";
      S = "https://tfngateway.ziroom.com/";
      ai = "https://tyezhu.ziroom.com/m/weituo.html?header=false&from_id=26";
      c = "https://tyzwebapi.ziroom.com/";
      L = "https://tupin.ziroom.com/";
      Z = "https://tapppush.ziroom.com/";
      g = "https://tphoenix.ziroom.com/";
      i = j + "API/";
      z = j;
      A = j;
      H = O;
      v = t;
      K = "b29df42e480325d2e8fb6fa17fba037f";
      I = Q;
      m = "http://s.m.swx.t.ziroom.com/";
      n = "http://s.m.t.ziroom.com/";
      R = Q;
      P = "b29df42e480325d2e8fb6fa17fba037f";
      W = "http://webapp.webapi.fp001.qa.ziroom.com/";
      aa = "https://contentful.ziroom.com/staging/zuzhu/bjapp/ucenter/a1d0c6e83f027327d8461063f4ac58a6.json";
      o = "https://ttoread.ziroom.com/";
      p = "http://ia.t.ziroom.com/robot/h5chat_ZR.html?sysNum=1476067342641247";
      al = "https://tcoupon.ziroom.com/";
      F = "http://zra.api.t.ziroom.com/";
      ap = "http://tkaleido.ziroom.com";
      M = "https://tmbs.ziroom.com/";
      X = "http://www.t.ziroom.com/";
      Y = "http://www.t.ziroom.com/";
      aj = "http://contentful.ziroom.com/staging/zuzhu/bjapp/3a029f04d76d32e79367c4b3255dda4d.json";
      as = "http://i.webapi.qa.ziroom.com/";
      ar = "http://www.t.ziroom.com/zhuanti/";
      am = "http://installment.t.ziroom.com/";
      return;
    }
    if (3 == h.getsEnvironment())
    {
      a = "https://qinterfaces.ziroom.com/";
      D = "https://qpay.ziroom.com/";
      j = "https://qsmsapis.ziroom.com/";
      r = "https://qes.ziroom.com/";
      U = r;
      s = "https://qcrm.ziroom.com/crm/";
      t = s;
      u = "https://qcmch.ziroom.com/";
      V = "https://qpassport.ziroom.com/";
      x = V;
      y = V;
      k = "https://qzmcapi.ziroom.com/";
      T = "https://qzryapi.ziroom.com/";
      B = T;
      E = "https://qzraapi.ziroom.com/";
      b = "https://qphoenix.ziroom.com/";
      h = b;
      e = "https://qmucenter.ziroom.com/";
      O = "https://qucenter.ziroom.com/";
      J = "https://wx.ziroom.com/";
      l = "https://qmovessmsapis.ziroom.com/";
      G = "https://qprop.ziroom.com/";
      Q = "https://qkaleido.ziroom.com/";
      q = "http://s.m.q.ziroom.com/";
      C = "https://qbnbapi.ziroom.com/";
      S = "https://qfngateway.ziroom.com/";
      ai = "https://qyezhu.ziroom.com/m/weituo.html?header=false&from_id=26";
      c = "https://qyzwebapi.ziroom.com/";
      L = "https://qupin.ziroom.com/";
      Z = "https://qapppush.ziroom.com/";
      g = "https://qphoenix.ziroom.com/";
      i = j + "API/";
      z = j;
      A = j;
      v = t;
      H = O;
      I = Q;
      m = "http://s.m.swx.q.ziroom.com/";
      n = "http://s.m.q.ziroom.com/";
      R = Q;
      W = "http://webapp.webapi.qa.ziroom.com/";
      K = "8f5dc0a1d869360ec5ccad9ac302f718";
      P = "8f5dc0a1d869360ec5ccad9ac302f718";
      aa = "http://contentful.ziroom.com/preprod/zuzhu/bjapp/ucenter/a1d0c6e83f027327d8461063f4ac58a6.json";
      an = "https://qwx.ziroom.com/";
      o = "http://toread.q.ziroom.com/";
      p = "http://ia.q.ziroom.com/robot/h5chat_ZR.html?sysNum=1476067342641247";
      al = "https://qcoupon.ziroom.com/";
      ap = "http://qkaleido.ziroom.com";
      M = "https://qmbs.ziroom.com/";
      X = "http://www.q.ziroom.com/";
      Y = "http://www.q.ziroom.com/";
      aj = "http://contentful.ziroom.com/preprod/zuzhu/bjapp/3a029f04d76d32e79367c4b3255dda4d.json";
      as = "http://i.webapi.prepord.ziroom.com/";
      F = "http://zra.api.q.ziroom.com/";
      ar = "http://www.q.ziroom.com/zhuanti/";
      am = "http://installment.q.ziroom.com/";
      return;
    }
    if (4 == h.getsEnvironment())
    {
      a = "https://interfaces.ziroom.com/";
      D = "https://pay.ziroom.com/";
      j = "https://smsapis.ziroom.com/";
      r = "https://es.ziroom.com/";
      U = r;
      s = "https://crm.ziroom.com/crm/";
      t = s;
      u = "https://cmch.ziroom.com/";
      V = "https://passport.ziroom.com/";
      x = V;
      y = V;
      k = "https://zmcapi.ziroom.com/";
      T = "https://zryapi.ziroom.com/";
      B = T;
      E = "https://zraapi.ziroom.com/";
      b = "https://phoenix.ziroom.com/";
      h = b;
      e = "https://mucenter.ziroom.com/";
      O = "https://ucenter.ziroom.com/";
      J = "https://wx.ziroom.com/";
      l = "https://movessmsapis.ziroom.com/";
      G = "https://prop.ziroom.com/";
      Q = "https://kaleido.ziroom.com/";
      q = "http://s.m.ziroom.com/";
      C = "https://bnbapi.ziroom.com/";
      S = "https://fngateway.ziroom.com/";
      ai = "https://yezhu.ziroom.com/m/weituo.html?header=false&from_id=26";
      c = "https://yzwebapi.ziroom.com/";
      L = "https://upin.ziroom.com/";
      Z = "https://apppush.ziroom.com/";
      g = "https://phoenix.ziroom.com/";
      i = j + "API/";
      z = j;
      A = j;
      v = t;
      H = O;
      I = Q;
      m = "https://smswx.ziroom.com/";
      n = "https://sm.ziroom.com/";
      R = Q;
      K = "8f5dc0a1d869360ec5ccad9ac302f718";
      P = "8f5dc0a1d869360ec5ccad9ac302f718";
      W = "http://webapp.webapi.ziroom.com/";
      aa = "http://contentful.ziroom.com/online/zuzhu/bjapp/ucenter/a1d0c6e83f027327d8461063f4ac58a6.json";
      an = "https://wx.ziroom.com/";
      o = "https://ztoread.ziroom.com/";
      p = "http://ia.ziroom.com/robot/h5chat_ZR.html?sysNum=1476067342641247";
      al = "https://coupon.ziroom.com/";
      ap = "http://kaleido.ziroom.com";
      M = "https://mbs.ziroom.com/";
      X = "http://zhuanti.ziroom.com/";
      Y = "http://www.ziroom.com/";
      aj = "http://contentful.ziroom.com/online/zuzhu/bjapp/3a029f04d76d32e79367c4b3255dda4d.json";
      as = "http://i.webapi.ziroom.com/";
      ar = "https://hd.ziroom.com/";
      F = E;
      am = "http://installment.ziroom.com/";
      return;
    }
    a = "https://interfaces.ziroom.com/";
    D = "https://pay.ziroom.com/";
    j = "https://smsapis.ziroom.com/";
    r = "https://es.ziroom.com/";
    s = "https://crm.ziroom.com/crm/";
    t = s;
    u = "https://cmch.ziroom.com/";
    V = "http://passport.ziroom.com/";
    x = V;
    y = V;
    k = "https://zmcapi.ziroom.com/";
    T = "https://zryapi.ziroom.com/";
    B = T;
    E = "https://zraapi.ziroom.com/";
    b = "https://phoenix.ziroom.com/";
    h = b;
    e = "https://mucenter.ziroom.com/";
    O = "https://ucenter.ziroom.com/";
    J = "https://wx.ziroom.com/";
    l = "https://movessmsapis.ziroom.com/";
    G = "https://prop.ziroom.com/";
    Q = "https://kaleido.ziroom.com/";
    q = "http://s.m.ziroom.com/";
    C = "https://bnbapi.ziroom.com/";
    S = "https://fngateway.ziroom.com/";
    ai = "https://yezhu.ziroom.com/m/weituo.html?header=false&from_id=26";
    c = "https://yzwebapi.ziroom.com/";
    L = "https://upin.ziroom.com/";
    Z = "https://apppush.ziroom.com/";
    g = "https://phoenix.ziroom.com/";
    i = j + "API/";
    z = j;
    A = j;
    v = t;
    H = O;
    K = "8f5dc0a1d869360ec5ccad9ac302f718";
    I = Q;
    m = "https://smswx.ziroom.com/";
    n = "https://sm.ziroom.com/";
    R = Q;
    P = "8f5dc0a1d869360ec5ccad9ac302f718";
    W = "http://webapp.webapi.ziroom.com/";
    an = "https://wx.ziroom.com/";
    o = "https://ztoread.ziroom.com/";
    al = "https://coupon.ziroom.com/";
    ap = "http://kaleido.ziroom.com";
    M = "https://mbs.ziroom.com/";
    X = "http://zhuanti.ziroom.com/";
    Y = "http://www.ziroom.com/";
    aj = "http://contentful.ziroom.com/online/zuzhu/bjapp/3a029f04d76d32e79367c4b3255dda4d.json";
    as = "http://i.webapi.ziroom.com/";
    p = "http://ia.ziroom.com/robot/h5chat_ZR.html?sysNum=1476067342641247";
    F = E;
    ar = "https://hd.ziroom.com/";
    am = "http://installment.ziroom.com/";
  }
}


/* Location:              /Users/gaoht/Downloads/zirom/classes2-dex2jar.jar!/com/ziroom/ziroomcustomer/e/q.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */